server:
  port: 8070

  # base context-path
  servlet:
    context-path: /sleuth

  # tmp path
  tomcat:
    basedir: "tmp"

spring:
  application:
    name: consumer-service

  zipkin:
    base-url: http://127.0.0.1:9411/

  kafka:
    bootstrap-servers: 127.0.0.1:19092,127.0.0.1:19093,127.0.0.1:19094,127.0.0.1:19095
    producer:
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
#      group-id: sleuth_zipkin_consumer_group_2
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

topic:
  scenarios:
    -
      scenario:
        -
          name: SLEUTH_ZIPKIN_TOPIC_CASE_1_1
          consumer-group: sleuth_zipkin_consumer_group_case_1_1
    -
      scenario:
        - name: SLEUTH_ZIPKIN_TOPIC_CASE_2_1
          consumer-group: sleuth_zipkin_consumer_group_case_2_1
        - name: SLEUTH_ZIPKIN_TOPIC_CASE_2_2
          consumer-group: sleuth_zipkin_consumer_group_case_2_2
    -
      scenario:
        - name: SLEUTH_ZIPKIN_TOPIC_CASE_3_1
          consumer-group: sleuth_zipkin_consumer_group_case_3_1
        - name: SLEUTH_ZIPKIN_TOPIC_CASE_3_2
          consumer-group: sleuth_zipkin_consumer_group_case_3_2
        - name: SLEUTH_ZIPKIN_TOPIC_CASE_3_3
          consumer-group: sleuth_zipkin_consumer_group_case_3_3

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus