server:
  tomcat:
    basedir: "tmp"

spring:
  application:
    name: streams-service

  zipkin:
    base-url: http://192.168.0.111:9411/

  kafka:
    bootstrap-servers: 192.168.0.111:9092,192.168.0.111:9093,192.168.0.111:9094,192.168.0.111:9095
    streams:
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      application-id: ${topic.scenarios[1].scenario.[0].consumer-group} #sleuth_zipkin_consumer_group

topic:
  scenarios:
    -
      scenario:
        -
          name: SLEUTH_ZIPKIN_TOPIC_CASE_1_1
          consumer-group: sleuth_zipkin_consumer_group_case_1_1
    -
      scenario:
        - name: SLEUTH_ZIPKIN_TOPIC_CASE_2_1
          consumer-group: sleuth_zipkin_consumer_group_case_2_1
        - name: SLEUTH_ZIPKIN_TOPIC_CASE_2_2
          consumer-group: sleuth_zipkin_consumer_group_case_2_2
    -
      scenario:
        - name: SLEUTH_ZIPKIN_TOPIC_CASE_3_1
          consumer-group: sleuth_zipkin_consumer_group_case_3_1
        - name: SLEUTH_ZIPKIN_TOPIC_CASE_3_2
          consumer-group: sleuth_zipkin_consumer_group_case_3_2
        - name: SLEUTH_ZIPKIN_TOPIC_CASE_3_3
          consumer-group: sleuth_zipkin_consumer_group_case_3_3